### PR TITLE
Update PDOK-Luchtfoto-Beeldmateriaal-25cm-latest.json

### PR DESCRIPTION
**Pull request by AllroadsNL**
Change url, old one is not working from today.
https://github.com/osmlab/editor-layer-index/pull/1152/files

### CODE REVIEW

**Comment by bhousel** [comment]
This repo isn't really used for anything, but thanks anyway! 👍

**Comment by AllroadsNL** [comment]
What is used? Where to watch?

First I only did a pull request for OSMlab, but that was not picked up by ID.

**Comment by AllroadsNL** [comment]
Over a couple of months we get a 7,5 cm aerial from PDOK.
Where to set up the new layer?

**Comment by boothym** [comment]
@AllroadsNL I think it's https://github.com/osmlab/editor-layer-index that you are looking for 😉

**Pull request merged**
