### PR TITLE
Don't use SVN for FR-Cadastre icon

### PR DESCRIPTION
**Pull request by Firefishy**
svn.openstreetmap.org is gone. Replace icon.

### CODE REVIEW

**Comment by Firefishy** [comment]
Bump ;-)

**Comment by Firefishy** [comment]
@bhousel Any love? ;-)

**Comment by bhousel** [comment]
Ok, but we dont use this project anywhere.

**Comment by Firefishy** [comment]
> Ok, but we dont use this project anywhere.

Oh! Sorry, I thought it was in use. Difficult to tell as an outsider what is and what isn't in use.

**Pull request merged**
