### PR TITLE
Change Spain PNOA source to cached JPEGs

### PR DESCRIPTION
**Pull request by jsanz**
I was contacted by Spanish NMA (IGN/CNIG) to try to change the format of the imagery requests for the Spanish default source (`PNOA Spain`) from `image/png` to `image/jpeg` since the latter is cached on their CDN.

### CODE REVIEW

**Comment by Johnbo** [comment]
This is a big necessity. PNOA is the most accurate imagery in Spain, but it takes centuries to load all tiles while editing with iD.

**Comment by bhousel** [comment]
I'm happy to accept your pull request, but unfortunately this repo never got used by iD.

I built it last year as a way to reduce the amount of polygon geometry, produce correct geojson geometry, and publish releases with version numbers.  This would have enabled us to push out compatible imagery updates to users at any time rather than bundling in the editor-layer-index whenever iD releases occur.

You can read more about it here:
https://github.com/openstreetmap/iD/issues/7425
https://github.com/openstreetmap/iD/pull/7428

Most people know by now, but I was fired from my job over this and had my iD maintainer role removed.

**Comment by jsanz** [comment]
Thanks, @bhousel for the details, much appreciated. I'm sorry I was not aware of all the history and wrongly assumed where the sources are coming to iD.

The correct location to propose the change is then at https://github.com/osmlab/editor-layer-index, right? I just want to help Spanish users (and IGN/CGNIG people) to get a fluent experience when editing. 

Thanks again!

**Comment by jsanz** [comment]
I went ahead and created (I hope for good this time) a new PR with the same change at https://github.com/osmlab/editor-layer-index/pull/1121

**Pull request merged**
